name: build

on:
  - push

env:
  GO_VERSION: 1.18
  CGO_ENABLED: 0
  IMAGE_REPOSITORY: sosedoff/pgweb

jobs:
  docker-build:
    name: docker images
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configure docker build context
        uses: docker/setup-buildx-action@v2

      - name: Build docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: pgweb:latest
          platforms: darwin/amd64,darwin/arm64,linux/amd64,linux/arm64,linux/arm/v5,linux/arm/v7,linux/386
