name: Build

on:
  - push

env:
  GO_VERSION: 1.18
  CGO_ENABLED: 0
  IMAGE_REPOSITORY: sosedoff/pgweb

jobs:
  docker-build:
    name: Publish Docker images
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure docker build context
        uses: docker/setup-buildx-action@v1

      - name: Build docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: pgweb:latest
          platforms: linux/amd64,linux/arm64
